list: $/timfoerster/leaflet/models/objects/columns.yaml
modelClass: TimFoerster\Leaflet\Models\Objects
title: Objects
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'timfoerster/leaflet/objects/update/:id'
