title: Maps
modelClass: TimFoerster\Leaflet\Models\Maps
list: $/timfoerster/leaflet/models/maps/columns.yaml
recordUrl: 'timfoerster/leaflet/maps/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
showSorting: 1
defaultSort:
    column: name
    direction: asc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
